"""
PDF Converter for Diary System
Bridges TypeScript-generated HTML/JSON to Python WeasyPrint PDF generation
"""
import json
import sys
import os
from pathlib import Path
from typing import Dict, Any, Optional
from datetime import datetime

# Add pdf-generator to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent / "pdf-generator"))
from generator import PDFGenerator

class DiaryPdfConverter:
    """Convert diary HTML/JSON to PDF using WeasyPrint"""
    
    def __init__(self):
        self.generator = PDFGenerator()
        self.output_dir = Path(__file__).parent / "test_output"
        self.output_dir.mkdir(exist_ok=True)
    
    def convert_daily_html_to_pdf(self, html_path: str, output_path: Optional[str] = None) -> Dict[str, Any]:
        """
        Convert daily diary HTML to PDF
        
        Args:
            html_path: Path to HTML file generated by TypeScript renderer
            output_path: Optional output path for PDF
            
        Returns:
            Result dictionary with success status and file path
        """
        try:
            html_file = Path(html_path)
            if not html_file.exists():
                return {
                    "success": False,
                    "error": f"HTML file not found: {html_path}"
                }
            
            # Generate output path if not provided
            if not output_path:
                output_path = str(html_file.with_suffix('.pdf'))
            
            # Read HTML content
            with open(html_file, 'r', encoding='utf-8') as f:
                html_content = f.read()
            
            # Use WeasyPrint to convert HTML to PDF
            from weasyprint import HTML, CSS
            
            # Generate PDF directly from HTML
            HTML(string=html_content).write_pdf(output_path)
            
            return {
                "success": True,
                "outputPath": output_path,
                "fileSize": os.path.getsize(output_path)
            }
            
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }
    
    def convert_daily_json_to_pdf(self, json_path: str, output_path: Optional[str] = None) -> Dict[str, Any]:
        """
        Convert daily diary JSON to PDF using existing generator
        
        Args:
            json_path: Path to JSON file with DailyDiaryPayload
            output_path: Optional output path for PDF
            
        Returns:
            Result dictionary with success status and file path
        """
        try:
            json_file = Path(json_path)
            if not json_file.exists():
                return {
                    "success": False,
                    "error": f"JSON file not found: {json_path}"
                }
            
            # Load JSON content
            with open(json_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            # Generate output path if not provided
            if not output_path:
                output_path = str(json_file.with_suffix('.pdf'))
            
            # Convert to format expected by generator
            content = self._convert_payload_to_content(data)
            
            # Generate PDF using existing generator
            result_path = self.generator.generate_daily_pdf(
                content=content,
                output_path=output_path,
                role=data.get('metadata', {}).get('role', 'student')
            )
            
            return {
                "success": True,
                "outputPath": result_path,
                "fileSize": os.path.getsize(result_path)
            }
            
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }
    
    def convert_period_html_to_pdf(self, html_path: str, output_path: Optional[str] = None) -> Dict[str, Any]:
        """
        Convert period diary HTML bundle to PDF
        
        Args:
            html_path: Path to HTML file with multiple pages
            output_path: Optional output path for PDF
            
        Returns:
            Result dictionary with success status and file path
        """
        try:
            html_file = Path(html_path)
            if not html_file.exists():
                return {
                    "success": False,
                    "error": f"HTML file not found: {html_path}"
                }
            
            # Generate output path if not provided
            if not output_path:
                output_path = str(html_file.with_suffix('.pdf'))
            
            # Read HTML content
            with open(html_file, 'r', encoding='utf-8') as f:
                html_content = f.read()
            
            # Use WeasyPrint to convert HTML to PDF with print styles
            from weasyprint import HTML, CSS
            
            # Add print-specific CSS for page breaks
            print_css = CSS(string="""
                @page {
                    size: A4;
                    margin: 20mm;
                }
                .page-break {
                    page-break-after: always;
                }
                .cover-page {
                    page-break-after: always;
                }
                .daily-page {
                    page-break-after: always;
                }
            """)
            
            # Generate PDF with print styles
            HTML(string=html_content).write_pdf(
                output_path,
                stylesheets=[print_css]
            )
            
            return {
                "success": True,
                "outputPath": output_path,
                "fileSize": os.path.getsize(output_path),
                "pageCount": self._estimate_page_count(html_content)
            }
            
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }
    
    def _convert_payload_to_content(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Convert DailyDiaryPayload to content format expected by generator
        """
        # Extract content from payload
        content = payload.get('content', {})
        
        # Map to generator's expected format
        return {
            "date": payload.get('date', ''),
            "summary": content.get('summary', ''),
            "keywords": content.get('keywords', []),
            "rhythm_description": content.get('rhythmDescription', ''),
            "focus_caution": {
                "focus": content.get('focusCaution', {}).get('focus', []),
                "caution": content.get('focusCaution', {}).get('caution', [])
            },
            "action_guide": {
                "do": content.get('actionGuide', {}).get('do', []),
                "avoid": content.get('actionGuide', {}).get('avoid', [])
            },
            "time_direction": content.get('timeDirection', {}),
            "state_trigger": content.get('stateTrigger', {}),
            "meaning_shift": content.get('meaningShift', ''),
            "rhythm_question": content.get('rhythmQuestion', '')
        }
    
    def _estimate_page_count(self, html_content: str) -> int:
        """
        Estimate page count from HTML content
        """
        # Count page break elements
        page_breaks = html_content.count('page-break-after')
        # Add 1 for the last page (no break after)
        return page_breaks + 1


def main():
    """Test the PDF converter"""
    converter = DiaryPdfConverter()
    
    # Test paths
    test_html = Path(__file__).parent / "test_output" / "test_1week_1735286567841.html"
    test_json = Path(__file__).parent / "test_output" / "test_daily.json"
    
    # Test HTML to PDF conversion if HTML exists
    if test_html.exists():
        print(f"Testing HTML to PDF conversion: {test_html}")
        result = converter.convert_period_html_to_pdf(str(test_html))
        if result["success"]:
            print(f"✅ PDF generated: {result['outputPath']}")
            print(f"   File size: {result['fileSize']} bytes")
            if 'pageCount' in result:
                print(f"   Page count: {result['pageCount']}")
        else:
            print(f"❌ Failed: {result['error']}")
    else:
        print(f"⚠️ Test HTML not found: {test_html}")
        print("   Run the TypeScript tests first to generate HTML files")
    
    # Create a sample JSON for testing
    sample_json = {
        "date": "2026-03-28",
        "metadata": {
            "role": "student",
            "generatedAt": datetime.now().isoformat()
        },
        "content": {
            "summary": "오늘은 집중력이 높은 날입니다.",
            "keywords": ["집중", "학습", "정리"],
            "rhythmDescription": "안정적인 흐름이 이어집니다.",
            "focusCaution": {
                "focus": ["중요한 과제 완성", "복습 시간"],
                "caution": ["과도한 스트레스", "늦은 밤 공부"]
            },
            "actionGuide": {
                "do": ["오전 시간 활용", "계획적인 학습"],
                "avoid": ["미루기", "산만한 환경"]
            },
            "timeDirection": {
                "good_time": "오전 9-11시",
                "avoid_time": "오후 3-5시",
                "good_direction": "북쪽",
                "avoid_direction": "남서쪽"
            },
            "stateTrigger": {
                "gesture": "심호흡 3회",
                "phrase": "차분하게 집중하자",
                "how_to": "공부 시작 전 실행"
            },
            "meaningShift": "불안은 준비의 신호입니다.",
            "rhythmQuestion": "오늘 가장 집중하고 싶은 것은?"
        }
    }
    
    # Save sample JSON
    sample_json_path = converter.output_dir / "sample_daily.json"
    with open(sample_json_path, 'w', encoding='utf-8') as f:
        json.dump(sample_json, f, ensure_ascii=False, indent=2)
    
    # Test JSON to PDF conversion
    print(f"\nTesting JSON to PDF conversion: {sample_json_path}")
    result = converter.convert_daily_json_to_pdf(str(sample_json_path))
    if result["success"]:
        print(f"✅ PDF generated: {result['outputPath']}")
        print(f"   File size: {result['fileSize']} bytes")
    else:
        print(f"❌ Failed: {result['error']}")


if __name__ == "__main__":
    main()